### ISSUE TITLE
White screen after loading PDF anly API 21

### ISSUE THREAD

**Issue by Vasilisk7** [AbdOoSaed/flutter_cached_pdfview#67]
v.0.4.1
I download pdf via url, everything works fine.

But **only on API 21** after loading a white screen remains and that's it
I attach screenshots of the code, logs and screen.
Sorry for the quality, I take pictures from my work laptop.

![IMG_20211214_151015](https://user-images.githubusercontent.com/35864378/145996387-6d69211c-c055-4940-b040-f34a74d56cf8.jpg)
![IMG_20211214_151144](https://user-images.githubusercontent.com/35864378/145996394-804a8c8e-5bc9-4883-b64d-9e2db86d17d8.jpg)
![IMG_20211214_151043](https://user-images.githubusercontent.com/35864378/145996397-e5a2411d-e504-49ba-877d-5129191d10d9.jpg)

**Comment by AbdOoSaed** [comment]
Hi @Vasilisk7 
please download [example project](https://github.com/AbdOoSaed/flutter_cached_pdfview/tree/master/example)
and run it to check if it has the same issue

**Comment by Vasilisk7** [comment]
I downloaded the example and checked it on API 21, the problem **persists**, I attach a video

https://user-images.githubusercontent.com/35864378/146187310-18718e79-98e3-44a2-ae49-e4cf8feaae3f.mp4


https://user-images.githubusercontent.com/35864378/146187318-8e4a66f5-7cb1-4f23-905d-02c7f83c3071.mp4

**Comment by AbdOoSaed** [comment]
please tell me what is the flutter version you use 
` flutter --version`

are you find the same issue with the real devices?

**Comment by Vasilisk7** [comment]
Flutter 2.8.0
Dart 2.15.0

On a real device API 21 there is no way to check (no device).
On API 29-30 on a real device everything works.

**Comment by nachikamod** [comment]
Having the same issue with version 0.4.1

**Comment by nachikamod** [comment]
Ok seems like I was messing up with URL and that is why the widget was rendering blank, my issue is solved

**Comment by Vasilisk7** [comment]
My problem is still not solved :(

**Comment by Vasilisk7** [comment]
> 

I downloaded the demo project and ran it without changing anything. The problem persists, this is all I described above.

**Comment by ajdakter** [comment]
> Having the same issue with version 0.4.1 On Android 11 API 30

I have same problem, how can I solve ?
Android 11 API 30

**Comment by colbapnauj** [comment]
same issue, It worked in debug mode, but in release didn't. I included the proguard configuration but don't work

**Comment by YuhooZhu** [comment]
> > 
> 
> I downloaded the demo project and ran it without changing anything. The problem persists, this is all I described above.

same issue,have you solved? It seems cann't use in API 21

**Comment by MaximilianFlechtner** [comment]
+1
